/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Jarras;

import controlador.jarras.ArbolJarras;
import controlador.jarras.NodoJarras;

/**
 *
 * @author javisarango
 */
public class Frm_Jarras extends javax.swing.JDialog {

    private ArbolJarras arbolJarras;
    private NodoJarras estadoI = new NodoJarras();
    private NodoJarras estadoF = new NodoJarras();

    /**
     * Creates new form Frm_Jarras
     */
    public Frm_Jarras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private void cargarCombos() {
        Integer jg = estadoI.getJarraG().getCapacidad();
        Integer jp = estadoI.getJarraP().getCapacidad();
        cbxJGF.removeAllItems();
        cbxJGI.removeAllItems();
        cbxJPF.removeAllItems();
        cbxJPI.removeAllItems();
        for (int i = 0; i <= jg; i++) {
            cbxJGI.addItem(String.valueOf(i));
            cbxJGF.addItem(String.valueOf(i));
        }
        for (int i = 0; i < jp; i++) {
            cbxJPI.addItem(String.valueOf(i));
            cbxJPF.addItem(String.valueOf(i));
        }
    }
    private void busqueda(){
    estadoI = new NodoJarras(Integer.parseInt(cbxJGI.getSelectedItem().toString()),Integer.parseInt(cbxJPI.getSelectedItem().toString()));
    estadoF = new NodoJarras(Integer.parseInt(cbxJGF.getSelectedItem().toString()),Integer.parseInt(cbxJPF.getSelectedItem().toString()));
    arbolJarras = new ArbolJarras(estadoI, estadoF);
        try {
           // NodoJarras = 
        } catch (Exception e) {
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbxJGI = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxJPI = new javax.swing.JComboBox<>();
        cbxJGF = new javax.swing.JComboBox<>();
        cbxJPF = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estados"));
        jPanel2.setLayout(null);

        jLabel1.setText("Inicial:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(12, 25, 53, 27);

        cbxJGI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxJGI);
        cbxJGI.setBounds(70, 30, 70, 30);

        jLabel2.setText("Final:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, 30, 50, 30);

        cbxJPI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxJPI);
        cbxJPI.setBounds(140, 30, 70, 30);

        cbxJGF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxJGF);
        cbxJGF.setBounds(280, 30, 72, 30);

        cbxJPF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cbxJPF);
        cbxJPF.setBounds(360, 30, 72, 30);

        jButton1.setText("jButton1");
        jPanel2.add(jButton1);
        jButton1.setBounds(450, 30, 78, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 560, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 380);

        setSize(new java.awt.Dimension(592, 414));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Jarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Jarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Jarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Jarras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_Jarras dialog = new Frm_Jarras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxJGF;
    private javax.swing.JComboBox<String> cbxJGI;
    private javax.swing.JComboBox<String> cbxJPF;
    private javax.swing.JComboBox<String> cbxJPI;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
